-- MySQL Script generated by MySQL Workbench
-- Fri Feb 23 01:03:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sb_between
-- -----------------------------------------------------
-- ios_study

-- -----------------------------------------------------
-- Schema sb_between
--
-- ios_study
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sb_between` DEFAULT CHARACTER SET utf8 ;
USE `sb_between` ;

-- -----------------------------------------------------
-- Table `sb_between`.`bt_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sb_between`.`bt_post` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `image_id` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sb_between`.`bt_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sb_between`.`bt_file` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(45) NOT NULL,
  `file_ori_name` VARCHAR(45) NOT NULL,
  `file_ext` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`file_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sb_between`.`bt_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sb_between`.`bt_user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `couple_email` VARCHAR(45) NOT NULL,
  `status_code` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `profile_file_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_bt_user_bt_file_idx` (`profile_file_id` ASC),
  CONSTRAINT `fk_bt_user_bt_file`
    FOREIGN KEY (`profile_file_id`)
    REFERENCES `sb_between`.`bt_file` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
